name: Scheduled PDF Processor
on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 mins
  workflow_dispatch:        # Allows manual testing

jobs:
  wake-server:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Batch
        run: |
          curl -L --fail "https://velikhanov.pythonanywhere.com/api/trigger/?token=${{ secrets.TRIGGER_TOKEN }}"
